"""random message table

Revision ID: 15b8e9232f16
Revises: 71cd2d2ef03b
Create Date: 2021-02-13 21:02:38.210214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15b8e9232f16'
down_revision = '71cd2d2ef03b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('RandomMessages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('weaponType_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['weaponType_id'], ['WeaponTypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RandomMessages')
    # ### end Alembic commands ###
