"""table skins

Revision ID: 2d3009277416
Revises: dbb08c9feaff
Create Date: 2021-02-02 20:58:10.015497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d3009277416'
down_revision = 'dbb08c9feaff'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('Skins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('filterTerm', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('weapon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['weapon_id'], ['Weapons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Skins')
    # ### end Alembic commands ###
