"""table weapon

Revision ID: dbb08c9feaff
Revises: ddaffb17b356
Create Date: 2021-02-02 16:02:26.485445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbb08c9feaff'
down_revision = 'ddaffb17b356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Weapons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('store', sa.String(length=255), nullable=True),
    sa.Column('weaponType_id', sa.Integer(), nullable=False),
    sa.Column('filterTerm', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['weaponType_id'], ['WeaponTypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Weapons')
    # ### end Alembic commands ###
